# Generated by Django 3.2.15 on 2022-10-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20221001_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialpost',
            name='description',
            field=models.TextField(),
        ),
    ]
