# Generated by Django 3.2.15 on 2022-10-04 15:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_tutorialpost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/volendam/image/upload/v1663526963/tsgvlrz1ews9u371xyfj.jpg', max_length=255, verbose_name='image'),
        ),
    ]
